ktor {
    developmentMode = true

    deployment {
        port = 8082
        watch = [ example.com ]
    }

    application {
        modules = [ example.com.ApplicationKt.module ]
    }

    logging {
        level = DEBUG
    }
}

db {
    postgres {
        driver = "org.postgresql.Driver"
        url = "jdbc:postgresql://postgres:5432/electricfest"
        user = "postgres"
        password = "postgrespasswd"
    }

    mongo {
        password = "O63oJEUWEnUkukbW"
        cluster = "cluster0"
        user = "testuser"

        database {
            name = "electricfest"
        }
    }

    redis {
        host = ${?DB_REDIS_HOST}
        port = ${?DB_REDIS_PORT}
    }
}

dotenv {
    directory = "./resources"
    ignoreIfMalformed = true
    ignoreIfMissing = true
}

jwt {
    issuer = "http://auth.myapp.internal"
    domain = "http://api.myapp.internal"

    auth {
        audience = "api.users"
        realm = "users"
        authSecret = ${?AUTH_JWT_SECRET}
        accessExpiresMinutes = 120
        refreshExpiresHours = 168
    }

    publish {
        audience = "stream.publish"
        publishSecret = ${?PUBLISH_JWT_SECRET}
        accessExpiresMinutes = 15
    }

    moderation {
        publishSecret = ${?MODERATION_PUBLISH_SECRET}
    }
}


email {
    gmail {
        provider = "gmail"
        smtpHost = "smtp.gmail.com"
        smtpPort = 465
        smtpEmail = "myworkacc832@gmail.com"
        smtpPassword = "escurhioalnfeiue"
        fromAddress = "myworkacc832@gmail.com"
        startTlsEnabled = false
    }

    yahoo {
        provider = "yahoo"
        smtpHost = "smtp.mail.yahoo.com"
        smtpPort = 465
        smtpEmail = "your product/company email"
        smtpPassword = "intrigaminima8"
        fromAddress = "your product/company email"
        startTlsEnabled = false
    }
}